version: '3'

services:
  squid-proxy:
    build: .
    environment:
      - PORT=3128
      - SSH_PORT=22
      - SQUID_USER=admin
      - SQUID_PASS=admin
    image: thelebster/docker-squid-simple-proxy
    hostname: squid-proxy
    container_name: squid-proxy
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
        tag: squid-proxy
    # volumes:
    #   - ./var/cache:/var/spool/squid
    #   - ./var/log:/var/log/squid
    ports:
      - 3128:3128
      - 22:22
    networks:
      - httpsProxy
    
  nghttpx:
    image: ibule/nghttpx:v1.3
    hostname: nghttpx
    container_name: nghttpx
    volumes:
      - ./certs:/certs
    ports:
      - 9699:9699
    environment:
      - BIND_HOST=squid-proxy
      - BIND_PORT=3128
      - CERT=cert.crt
      - KEY=key.key
    networks:
      - httpsProxy
    restart: always
networks:
  httpsProxy: